---
title: "2019-3-6_exp002"
author: "Jeroen Middelbeek"
date: "3/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, root, include=FALSE, }
require("rprojroot") || utils::install.packages("rprojroot")
library(rprojroot)
root <- find_root_file(criterion = is_rstudio_project)
```

```{r, load dataset, echo = FALSE}

library(readxl)

results <- file.path(root, "data-raw/2019-3-6_exp002", "results_002.csv")
parameters <- file.path(root, "data-raw/2019-3-6_exp002", "parameters_002.xlsx")

```


```{r tidy, echo = FALSE}
library(tidyverse)

#open & read results.csv 
results.col <- read_csv(results, 
              col_names = TRUE)%>%
      separate(Label, into = c("stack_id","image_id"), sep=":")%>%
      separate(image_id, into = c("well_id" , "strain" , "dye" , "OD" , "trtmnt" , "well_rep", "image_rep"), sep="_") 
                   
#open & read parameters.xlsx                         
workbook <- readxl::excel_sheets(path = parameters)
data.col <- readxl::read_xlsx(path = parameters, sheet = workbook[2]) 

df <- results.col%>%
    select (X1, well_id, image_rep, Area)%>%
    left_join(data.col, by = "well_id")

#Mutate parameters  
df_filtered <- dplyr::filter(df, Area>0) %>% 
  mutate (od = as.factor(od)) %>%
  mutate (image_rep = as.factor(image_rep)) %>%
  mutate (well_rep = as.factor(well_rep)) %>%
  mutate (comp_dil = as.factor(comp_dil))

```

# Analysis of unfiltered data

```{r unfilterd analysis, echo = FALSE}

ggplot(data=df_filtered, mapping = aes(x = od)) +
  geom_bar(
    mapping = aes(color = well_rep, fill = well_rep),
    position = position_dodge(width=0.6), width=0.5) +
  ggtitle("Particle Count") +
  facet_grid(~comp_name, scale = "fixed")

ggplot(data=df_filtered, mapping = aes(x = od, y = log10(Area))) +
  geom_point(
    mapping = aes(color = well_rep), 
    alpha = 0.1, 
    position = "jitter" ) +
  ggtitle("Particle Size (log)") +
  facet_wrap(~ comp_name)

ggplot(data=df_filtered, mapping = aes(x = od, y = log10(Area))) +
  geom_point(
    alpha = 0.1, 
    position = "jitter" ) +
  ggtitle("Particle Size (log)") +
  facet_wrap(~ comp_name)

#SUMMARIZE
particle_size <- df_filtered%>%
  group_by(od, comp_name, well_rep, image_rep) %>%
  summarize( 
            size_mean = mean(Area, na.rm=TRUE),
            size_sd = sd(Area, na.rm=TRUE)
            )

#INTRARAWELL REPRODUCIBILITY
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean), colour = image_rep))+
  geom_boxplot()+
  ggtitle("Intrawell Reproducibility") +
  facet_wrap(well_rep~ comp_name)

#INTERWELL REPRODUCIBILITY
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean), colour = well_rep))+
  geom_boxplot()+
  ggtitle("Interwell Reproducibility") +
  facet_wrap(~ comp_name)

#SUMMARIZE
particle_size <- df_filtered%>%
  group_by(od, comp_name, well_rep) %>%
  summarize( 
            size_mean = mean(Area, na.rm=TRUE),
            size_sd = sd(Area, na.rm=TRUE)
            )

#EXPERIMENT
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean)))+
  geom_boxplot() +
  ggtitle("Experiment") +
  facet_wrap(~ comp_name)
```

# Analysis of filtered data

```{r filtered analysis, echo = FALSE}

#FILTER
df_filtered <- dplyr::filter(df_filtered, Area>0, well_id != "C9" & well_id != "D4" & well_id != "D5" & well_id != "D7")

ggplot(data=df_filtered, mapping = aes(x = od)) +
  geom_bar(
    mapping = aes(color = well_rep, fill = well_rep),
    position = position_dodge(width=0.6), width=0.5) +
  ggtitle("Particle Count") + 
  facet_grid(~comp_name, scale = "fixed")

ggplot(data=df_filtered, mapping = aes(x = od, y = log10(Area))) +
  geom_point(
    mapping = aes(color = well_rep), 
    alpha = 0.1, 
    position = "jitter" ) +
  ggtitle("Particle Size (log)") + 
  facet_wrap(~ comp_name)

ggplot(data=df_filtered, mapping = aes(x = od, y = log10(Area))) +
  geom_point(
    alpha = 0.1, 
    position = "jitter" )+
  ggtitle("Particle Size (log)") + 
  facet_wrap(~ comp_name)

#SUMMARIZE
particle_size <- df_filtered%>%
  group_by(od, comp_name, well_rep, image_rep) %>%
  summarize( 
            size_mean = mean(Area, na.rm=TRUE),
            size_sd = sd(Area, na.rm=TRUE)
            )

#INTRARAWELL REPRODUCIBILITY
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean), colour = image_rep))+
  geom_boxplot()+
  ggtitle("Intrawell Reproducibility") + 
  facet_wrap(well_rep ~ comp_name)

#INTERWELL REPRODUCIBILITY
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean), colour = well_rep))+
  geom_boxplot()+
  ggtitle("Interwell Reproducibility") +
  facet_wrap(~ comp_name)

#SUMMARIZE
particle_size <- df_filtered%>%
  group_by(od, comp_name, well_rep) %>%
  summarize( 
            size_mean = mean(Area, na.rm=TRUE),
            size_sd = sd(Area, na.rm=TRUE)
            )

#EXPERIMENT
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean)))+
  geom_boxplot() +
  ggtitle("Experiment") +
  facet_wrap(~ comp_name)
```