---
title: "Database_Test"
author: "Jeroen Middelbeek"
date: "3/12/2019"
output: html_document
---



```{r, root, include=FALSE}
require("rprojroot") || utils::install.packages("rprojroot")
library(rprojroot)
root <- find_root_file(criterion = is_rstudio_project)
```

```{r, load dataset}

library(readxl)

results <- file.path(root, "data-raw/2019-3-14_testconcentration", "results.csv")
parameters <- file.path(root, "data-raw/2019-2-22_testconcentration", "parameters.xlsx")



```


```{r tidy}
library(tidyverse)

results.col <- read_csv(results,               col_names = TRUE)%>%
      separate(Label, into = c("stack_id","image_id"), sep=":")%>%
      separate(image_id, into = c("exp_id","plate_id","well_id","image_rep"), sep="_") 
                   
                         
workbook <- readxl::excel_sheets(path = parameters)
data.col <- readxl::read_xlsx(path = parameters, sheet = workbook[2]) 

df <- results.col%>%
    select (X1, well_id, image_rep, Area)%>%
    left_join(data.col, by = "well_id")

df_filtered <- dplyr::filter(df, Area>100, well_id!="B6", well_id!="B2" | image_rep!="2") %>% 
  mutate (od = as.factor(od)) %>%
  mutate (image_rep = as.factor(image_rep)) %>%
  mutate (well_rep = as.factor(well_rep)) %>%
  mutate (comp_dil = as.factor(comp_dil))

df
```

```{r analysis}
ggplot(data=df_filtered, mapping = aes(x = od)) +
  geom_bar(
    mapping = aes(color = well_rep, fill = well_rep),
    position = position_dodge(width=0.6),
    width=0.5) +
  facet_grid(~comp_name, scale = "fixed")

ggplot(data=df_filtered, mapping = aes(x = od, y = log10(Area))) +
  geom_point(aes(colour = well_rep, alpha = 0.1), 
    # position = position_dodge(width=0.6)) +
    position = "jitter" )+
  facet_wrap(~ comp_name)

ggplot(data=df_filtered, mapping = aes(x = od, y = log10(Area))) +
  geom_point(aes(alpha = 0.001), 
    # position = position_dodge(width=0.6)) +
    position = "jitter" )+
  facet_wrap(~ comp_name)

particle_size <- df_filtered%>%
  group_by(od, comp_name, image_rep, well_rep) %>%
  summarize( 
            size_mean = mean(Area, na.rm=TRUE),
            size_sd = sd(Area, na.rm=TRUE)
            )

particle_size

#INTRARAWELL REPRODUCIBILITY
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean), colour = image_rep))+
  geom_boxplot()+
  #geom_errorbar(aes(ymin=(size_mean - size_sd), ymax=(size_mean + size_sd)), width=.2, position=position_dodge(.9))+
  facet_wrap(well_rep~ comp_name)

#INTERWELL REPRODUCIBILITY
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean), colour = well_rep))+
  geom_boxplot()+
  #geom_errorbar(aes(ymin=(size_mean - size_sd), ymax=(size_mean + size_sd)), width=.2, position=position_dodge(.9))+
  facet_wrap(~ comp_name)

#Experiment
ggplot(data=particle_size, mapping = aes(x=od, y = (size_mean)))+
  geom_boxplot()+
 # geom_errorbar(aes(ymin=(size_mean - size_sd), ymax=(size_mean + size_sd)), width=.2
 #               )+
  facet_wrap(~ comp_name)

```