---
title: "2019-5-22_exp018"
author: "Jeroen Middelbeek"
date: "5/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, root, include=FALSE}
require("rprojroot") || utils::install.packages("rprojroot")
library(rprojroot)
root <- find_root_file(criterion = is_rstudio_project)
```

```{r, load dataset, echo = FALSE}

library(readxl)

path_results <- file.path(root, "data-raw/2019-5-22_exp018", "results_018.csv")
path_parameters <- file.path(root, "data-raw/2019-5-22_exp018", "parameters_018.xlsx")

```

```{r, tidy, echo = FALSE}
library(tidyverse)

#open & read results.csv 
df_results <-   read_csv(path_results, 
                        col_names = TRUE)%>%
                separate(Label, into = c("stack_id","image_id"), sep=":")%>%
                separate(image_id, into = c("exp_id" , "plate_id" , "well_id" , "image_rep"), sep="_")
            

#image_repna <- results.col %>%  mutate(image_rep = ifelse(is.na(image_rep), 2, image_rep))
#View(image_repna)


#open & read parameters.xlsx                         
workbook <- readxl::excel_sheets(path = path_parameters)
df_parameters <-  readxl::read_xlsx(path = path_parameters, sheet = workbook[2]) %>%
                  tidyr::unite(compound, "comp_name", "comp_id", "comp_trtmnt", sep = "-")
                  

#join results & parameters
df <- df_results %>%
      select (X1, well_id, image_rep, Area)%>%
      left_join(df_parameters, by = "well_id")

#mutate parameters  
df_filtered <-  dplyr::filter(df, Area>0) %>% 
                dplyr::filter(dye != "fitc" )  %>% 
                #sample_frac(0.1) %>%
                mutate(od = as.factor(od)) %>%
                mutate(image_rep = as.factor(image_rep)) %>%
                mutate(well_rep = as.factor(well_rep)) 
                #mutate(image_rep = ifelse(is.na(image_rep), 1, image_rep)) 
                

#SUMMARIZE
sum_image_rep <- df_filtered %>%
                    group_by(od, comp_dil, compound, well_rep, image_rep) %>%
                    summarize( 
                          count = n(),
                          mean_area = mean(Area, na.rm=TRUE),
                          sd_area = sd(Area, na.rm=TRUE)
                    )

sum_well_rep <- sum_image_rep %>%
                    group_by(od, comp_dil, compound, well_rep) %>%
                    summarize( 
                          count = n(),
                          mean_image = mean(mean_area, na.rm=TRUE),
                          sd_image = sd(mean_area, na.rm=TRUE),
                          sem_image = sd(mean_area, na.rm=TRUE)/sqrt(n())
                          )

sum_exp <- sum_well_rep %>%
                    group_by(od, comp_dil, compound) %>%
                    summarize( 
                          count = n(),
                          mean_well = mean(mean_image, na.rm=TRUE),
                          sd_well = sd(mean_image, na.rm=TRUE),
                          sem_well = sd(mean_image, na.rm=TRUE)/sqrt(n())
                    )               
                
```

# Filter data

```{r, filter, echo = FALSE}

df_filtered <- dplyr::filter(df_filtered, Area>0)

```

# Analysis of data

```{r, analysis, echo = FALSE}

source(file = file.path(root, "r", "functionplot_all.R"))

x <- plot_all(n = "comp_dil")
x
```