---
title: "2019-3-6_exp002"
author: "Jeroen Middelbeek"
date: "3/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, root, include=FALSE}
require("rprojroot") || utils::install.packages("rprojroot")
library(rprojroot)
root <- find_root_file(criterion = is_rstudio_project)
```

```{r, load dataset, echo = FALSE}

library(readxl)

results <- file.path(root, "data-raw/2019-3-14_exp004", "results_004.csv")
parameters <- file.path(root, "data-raw/2019-3-14_exp004", "parameters_004.xlsx")

```


```{r tidy, echo = FALSE}
library(tidyverse)

#open & read results.csv 
results.col <- read_csv(results, 
              col_names = TRUE)%>%
      separate(Label, into = c("stack_id","image_id"), sep=":")%>%
      separate(image_id, into = c("exp_id" , "plate_id" , "well_id" , "image_rep"), sep="_") 
                   
#open & read parameters.xlsx                         
workbook <- readxl::excel_sheets(path = parameters)
data.col <- readxl::read_xlsx(path = parameters, sheet = workbook[2]) 

#join results & parameters
df <- results.col%>%
    select (X1, well_id, image_rep, Area)%>%
    left_join(data.col, by = "well_id")

#Mutate parameters  
df_filtered <- dplyr::filter(df, Area>0) %>% 
  mutate (od = as.factor(od)) %>%
  mutate (image_rep = as.factor(image_rep)) %>%
  mutate (well_rep = as.factor(well_rep)) %>%
  mutate (comp_dil = as.factor(comp_dil))

```

# Filter data

``` {r filter}

df_filtered <- dplyr::filter(df_filtered, Area>0, well_id != "B6", well_id != "B2" | image_rep != "2" )

```

# Analysis of data

```{r analysis, echo = FALSE}

# write.csv(df_filtered, "data/df_filtered_exp004")

source(file = file.path("r", "data_analysis.R"))

x <- plot_all()
x[[1]]
x[[2]]
x[[3]]
x[[4]]
x[[5]]
x[[6]]

```