---
title: "2019-4-12"
author: "Jeroen Middelbeek"
date: "4/26/2019"
output: html_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, root, include=FALSE}
require("rprojroot") || utils::install.packages("rprojroot")
library(rprojroot)
root <- find_root_file(criterion = is_rstudio_project)
```

```{r, load dataset, echo = FALSE}

library(readxl)

results <- file.path(root, "data-raw/2019-4-12_exp007", "results_007.csv")
parameters <- file.path(root, "data-raw/2019-4-12_exp007", "parameters_007.xlsx")

```

```{r, tidy, echo = FALSE}
library(tidyverse)

#open & read results.csv 
results.col <- read_csv(results, 
                        col_names = TRUE)%>%
              separate(Label, into = c("stack_id","image_id"), sep=":")%>%
              separate(image_id, into = c("exp_id" , "plate_id" , "well_id" , "image_rep"), sep="_") 
                   
#open & read parameters.xlsx                         
workbook <- readxl::excel_sheets(path = parameters)
data.col <- readxl::read_xlsx(path = parameters, sheet = workbook[2]) 

#join results & parameters
df <- results.col%>%
      select (X1, well_id, image_rep, Area)%>%
      left_join(data.col, by = "well_id")

#mutate parameters  
df_filtered <- dplyr::filter(df, Area>0) %>% 
               # sample_frac(0.01)%>%
                mutate (od = as.factor(od)) %>%
                mutate (image_rep = as.factor(image_rep)) %>%
                mutate (well_rep = as.factor(well_rep)) %>%
                mutate (comp_dil = as.factor(comp_dil))

```

# Filter data

```{r, filter, echo = FALSE}

df_filtered <- dplyr::filter(df_filtered, Area>10, image_rep != "1" )

```

# Analysis of data

```{r, analysis, echo = FALSE}

#source(file = here::here("r", "functionplot_all.R"))
source(file = file.path(root, "r", "functionplot_all.R"))

x <- plot_all(df = df_filtered, n = "comp_dil")
x
```