---
title: "exp022"
author: "Jeroen Middelbeek"
date: "21-6-2019"
output: html_document
params: 
      var1: 
      var2:
      area_cutoff: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, root, include=FALSE}
require("rprojroot") || utils::install.packages("rprojroot")
library(rprojroot)
root <- find_root_file(criterion = is_rstudio_project)
```

```{r, packages, include=FALSE}
library(readxl)
library(tidyverse)
library(ggridges)
library(here)
library(scales)
```

```{r, load dataset, echo = FALSE}

path_results <- file.path(root, "data-raw/exp022", "results_exp022.csv")
path_parameters <- file.path(root, "data-raw/exp022", "parameters_exp022.xlsx")

```

#TIDY DATA

```{r, tidy, echo = FALSE}

#open & read results.csv 
df_results <- read_csv(path_results, col_names = TRUE)%>%
                separate(Label, into = c("exp_id" , "plate_id" , "well_id" , "image_rep"), sep="_") 
#                separate(Label, into = c("stack_id","image_id"), sep=":") %>%
#                separate(image_id, into = c("exp_id" , "plate_id" , "well_id" , "image_rep"), sep="_") 
#              dplyr::mutate(plate_id = as.numeric(plate_id))

#df_results <- dplyr::filter(df_results, plate_id != 1 )
              
#open & read parameters.xlsx                         
workbook <- readxl::excel_sheets(path = path_parameters)
df_parameters <-  readxl::read_xlsx(path = path_parameters, sheet = workbook[2]) %>%
                  tidyr::unite(compound, "comp_name", "comp_id", "comp_trtmnt", sep = "-") %>%
                  dplyr::mutate(plate_id = as.numeric(plate_id))
                 
##df_parameters <- dplyr::filter(df_parameters, plate_id != 1 )


#JOIN RESULTS & PARAMETERS
df <- df_results %>%
      select (X1, well_id, image_rep, Area)%>%
      left_join(df_parameters, by = "well_id")

#FILTER & MUTATE
df_filtered <-  dplyr::filter(df, Area > params$area_cutoff, well_id != "E9" | image_rep != 2) %>%
                #sample_frac(0.1) %>%
                mutate(od_factor = as.factor(od)) %>%
                mutate(comp_dil_factor = as_factor(scientific(comp_dil, digits=3))) %>% 
                #mutate(comp_dil_factor = as_factor(as.character(comp_dil_num))) %>%              
                mutate(image_rep = as.factor(image_rep)) %>%
                mutate(well_rep = as.factor(well_rep)) 
               
df_filtered$comp_dil_num %>% unique()
df_filtered$comp_dil_factor %>% levels()

#mutate(image_rep = ifelse(is.na(image_rep), 1, image_rep)) 
                #dplyr::filter(df_results, plate_id != 1 )
            
#SUMMARIZE
sum_image_rep <- df_filtered %>%
                    group_by(od, comp_dil, compound, well_rep, image_rep) %>%
                    summarize( 
                          count = n(),
                          mean_area = mean(Area, na.rm=TRUE),
                          sd_area = sd(Area, na.rm=TRUE)
                    )

sum_well_rep <- sum_image_rep %>%
                    group_by(od, comp_dil, compound, well_rep) %>%
                    summarize( 
                          count = n(),
                          mean_image = mean(mean_area, na.rm=TRUE),
                          sd_image = sd(mean_area, na.rm=TRUE),
                          sem_image = sd(mean_area, na.rm=TRUE)/sqrt(n())
                          )

sum_exp <- sum_well_rep %>%
                    group_by(od, comp_dil, compound) %>%
                    summarize( 
                          count = n(),
                          mean_well = mean(mean_image, na.rm=TRUE),
                          sd_well = sd(mean_image, na.rm=TRUE),
                          sem_well = sd(mean_image, na.rm=TRUE)/sqrt(n())
                    )
```

# Analysis of data

```{r, analysis, echo = FALSE}

source(file = file.path(root, "r", "functionplot_all.R"))

x <- plot_all(n = "comp_dil")
x
```